# Generated by Django 4.2.1 on 2024-02-15 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_category_customer_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.category'),
        ),
    ]
