# Generated by Django 4.2.1 on 2024-02-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_owner_customer_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='iin',
            field=models.BigIntegerField(null=True),
        ),
    ]
