# Generated by Django 4.2.1 on 2024-02-24 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_alter_item_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Цена', 'verbose_name_plural': 'Цены на товары'},
        ),
        migrations.AlterModelOptions(
            name='sellinginfo',
            options={'verbose_name': 'Счет', 'verbose_name_plural': 'Покупки'},
        ),
        migrations.RemoveField(
            model_name='price',
            name='company',
        ),
        migrations.RemoveField(
            model_name='sellinginfo',
            name='items',
        ),
        migrations.AddField(
            model_name='sellinginfo',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='shipper',
            field=models.ForeignKey(blank=True, default=10000, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='market.shipper'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellinginfo',
            name='shipper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.shipper'),
            preserve_default=False,
        ),
    ]
