# Generated by Django 4.2.1 on 2024-02-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_shipper_alter_price_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellinginfo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('shipper', 'item')},
        ),
    ]
